#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/powerrangers.h"
#include "images/garbage.h"
#include "images/pikachu.h"
#include "images/ash.h"
#include "images/pokeball.h"
#include "images/ashh.h"


/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
   REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  
  enum gba_state state = START;
  struct place pokeball1 = {10, 10};
  struct place pikachu1 = {rand() % 140, rand() % 220};
  int timer = 10;
  char timerStr[30];
  int x = 60;
  int y = 70;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawImageDMA(0, 0, 240, 160, ashh);
        drawString(0, 0, "WELCOME TO POKEMON", YELLOW);
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          fillScreenDMA(BLACK);
          timer = 20;
          state = PLAY;
          }
        // state = ?
        break;
      case PLAY:
      fillScreenDMA(BLACK);
      

      drawImageDMA(pokeball1.row, pokeball1.col,POKEBALL_WIDTH, POKEBALL_HEIGHT, pokeball);
      drawImageDMA(pikachu1.row, pikachu1.col,PIKACHU_WIDTH, PIKACHU_HEIGHT, pikachu);

    if (vBlankCounter % 60 == 0) { // Increment the timer every second
      timer--;
    }
    snprintf(timerStr, sizeof(timerStr), "Time: %d", timer);
    drawString(120,70 , timerStr, WHITE); // Display the timer in the top right corner of the screen
        

       if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (pokeball1.col < 220) {
            pokeball1.col++;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (pokeball1.col > 0) {
            pokeball1.col--;
          }
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (pokeball1.row > 0) {
            pokeball1.row--;
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (pokeball1.row < 140) {
            pokeball1.row++;
          }
        }


      if (pokeball1.row + POKEBALL_HEIGHT >= pikachu1.row &&
          pokeball1.row <= pikachu1.row + PIKACHU_HEIGHT &&
          pokeball1.col + POKEBALL_WIDTH >= pikachu1.col &&
          pokeball1.col <= pikachu1.col + PIKACHU_WIDTH) {
        // Change state to WIN
        state = WIN;
      }
      if(timer == 0){
        state = LOSE;
      }
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          pikachu1.col = rand() % 220;
          pikachu1.row = rand() % 140;
          state = START;
      }



        // state = ?
        break;
      case WIN:
      fillScreenDMA(BLACK);
      drawImageDMA(0, 0, 240, 160, ash);
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          fillScreenDMA(BLACK);
          pikachu1.col = rand() % 220;
          pikachu1.row = rand() % 140;
          state = START;
      }


        // state = ?
        break;
      case LOSE:
      fillScreenDMA(BLACK);
      drawString(x, y, "Try Again", YELLOW);
      x++;
      y++;
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          fillScreenDMA(BLACK);
          pikachu1.col = rand() % 220;
          pikachu1.row = rand() % 140;
          state = START;
      }

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
